// client/src/components/LoadingBar.jsx
import React, { useEffect, useRef, useState } from "react";
import { onApiActivity } from "../api";

const HIDE_DELAY = 240;

export default function LoadingBar() {
    const [active, setActive] = useState(false);
    const [visible, setVisible] = useState(false);
    const hideTimeoutRef = useRef(null);
    const hasInteractedRef = useRef(false);

    useEffect(() => onApiActivity((value) => setActive(Boolean(value))), []);

    useEffect(() => {
        if (active) {
            hasInteractedRef.current = true;
            if (hideTimeoutRef.current) {
                clearTimeout(hideTimeoutRef.current);
                hideTimeoutRef.current = null;
            }
            setVisible(true);
            return undefined;
        }

        if (!hasInteractedRef.current) {
            return undefined;
        }

        hideTimeoutRef.current = window.setTimeout(() => {
            setVisible(false);
            hideTimeoutRef.current = null;
        }, HIDE_DELAY);

        return () => {
            if (hideTimeoutRef.current) {
                clearTimeout(hideTimeoutRef.current);
                hideTimeoutRef.current = null;
            }
        };
    }, [active]);

    useEffect(
        () => () => {
            if (hideTimeoutRef.current) {
                clearTimeout(hideTimeoutRef.current);
            }
        },
        []
    );

    const finishing = visible && !active;
    const className = [
        "loading-bar",
        visible ? "loading-bar--visible" : "",
        active ? "loading-bar--active" : "",
        finishing ? "loading-bar--finishing" : "",
    ]
        .filter(Boolean)
        .join(" ");

    return (
        <div className={className} role="presentation" aria-hidden="true">
            <div className="loading-bar__track">
                <div className="loading-bar__indicator" />
            </div>
        </div>
    );
}

// client/src/components/LoadingBar.vue
<template>
    <div :class="className" role="presentation" aria-hidden="true">
        <div class="loading-bar__track">
            <div class="loading-bar__indicator"></div>
        </div>
    </div>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { onApiActivity } from '../api';

const HIDE_DELAY = 240;

const active = ref(false);
const visible = ref(false);
const hideTimeoutRef = ref(null);
const hasInteractedRef = ref(false);
let unsubscribe = null;

function clearHideTimeout() {
    if (hideTimeoutRef.value !== null) {
        clearTimeout(hideTimeoutRef.value);
        hideTimeoutRef.value = null;
    }
}

onMounted(() => {
    unsubscribe = onApiActivity((value) => {
        active.value = Boolean(value);
    });
});

watch(
    active,
    (isActive) => {
        if (isActive) {
            hasInteractedRef.value = true;
            clearHideTimeout();
            visible.value = true;
            return;
        }

        if (!hasInteractedRef.value) {
            return;
        }

        clearHideTimeout();
        hideTimeoutRef.value = window.setTimeout(() => {
            visible.value = false;
            hideTimeoutRef.value = null;
        }, HIDE_DELAY);
    },
    { flush: 'post' }
);

onBeforeUnmount(() => {
    clearHideTimeout();
    if (unsubscribe) {
        unsubscribe();
        unsubscribe = null;
    }
});

const finishing = computed(() => visible.value && !active.value);

const className = computed(() =>
    [
        'loading-bar',
        visible.value ? 'loading-bar--visible' : '',
        active.value ? 'loading-bar--active' : '',
        finishing.value ? 'loading-bar--finishing' : '',
    ]
        .filter(Boolean)
        .join(' ')
);
</script>
